export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_ROOM_DATA: 'SET_ROOM_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_ROOM_DATA: 'RESET_ROOM_DATA',
	ADD_BOOKING: 'ADD_BOOKING',
	DELETE_BOOKING: 'DELETE_BOOKING',
	SET_DATE_RANGE: 'SET_DATE_RANGE',
}
